# fly.toml app configuration file generated for scrobblescope on 2026-02-11T18:57:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "scrobblescope"
primary_region = "yyz"

[build]

[deploy]
  release_command = "python init_db.py"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 512
