"""Inspect and, only on explicit request, install the docsync preflight hook.

``--check`` (also the default with no flags) is read-only: it resolves and
prints the hook directory Git will actually search from ``cwd``, discloses
every worktree Git knows about (a shared ``core.hooksPath`` or the default
common-directory ``hooks/`` affects all of them, not just the one the
installer happened to run from), and reports whether a wrapper already sits
at the target path. Nothing is written.

``--install`` performs the same disclosure and then, only when given
``--yes``, writes the generated wrapper -- this is the "requires acceptance
of disclosed common-hook scope" the task brief asks for: the scope is always
printed first, and a bare ``--install`` alone is a dry run.

The generated wrapper preserves this repository's existing Graphify hooks:
it never touches ``core.hooksPath``, and it refuses to overwrite a hook file
that is not one this installer generated (an "unknown" wrapper), rather than
guessing that it is safe to replace. See "Commit preflight" in
docs/superpowers/specs/2026-09-15-docsync-closeout-archives-design.md.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

from scripts.dev._worktree_guard_venv import (  # noqa: E402
    POSIX_TOOLS,
    WINDOWS_TOOLS,
    is_runnable,
)

Runner = Callable[..., subprocess.CompletedProcess]

#: Every generated wrapper carries this exact line, which is how the
#: installer tells its own output apart from a hand-written or third-party
#: hook -- see ``classify_existing_hook``.
GENERATED_MARKER = (
    "# Generated by scripts/dev/install_docsync_hook.py -- DOCSYNC PREFLIGHT WRAPPER."
)
HOOK_NAME = "pre-commit"
PREFLIGHT_SCRIPT = Path("scripts/dev/docsync_preflight.py")


class InstallerError(RuntimeError):
    """A precondition failed before inspection or installation could finish."""


# --------------------------------------------------------------------- #
# Git plumbing                                                           #
# --------------------------------------------------------------------- #


def _run_git(
    args: Sequence[str], *, cwd: Path, runner: Runner = subprocess.run
) -> subprocess.CompletedProcess:
    """Run one Git command as text and return its completed process."""
    return runner(
        ["git", *args], cwd=str(cwd), capture_output=True, text=True, check=False
    )


def git_common_dir(cwd: Path, *, runner: Runner = subprocess.run) -> Path:
    """Return the absolute common Git directory Git reports for ``cwd``."""
    result = _run_git(
        ["rev-parse", "--path-format=absolute", "--git-common-dir"],
        cwd=cwd,
        runner=runner,
    )
    if result.returncode != 0:
        raise InstallerError(
            f"git rev-parse --git-common-dir failed: {result.stderr.strip()}"
        )
    return Path(result.stdout.strip())


def primary_checkout_root(cwd: Path, *, runner: Runner = subprocess.run) -> Path:
    """Return the primary checkout for ``cwd`` (the common dir's parent)."""
    return git_common_dir(cwd, runner=runner).parent


def repo_root(cwd: Path, *, runner: Runner = subprocess.run) -> Path:
    """Return the working tree root Git reports for ``cwd``."""
    result = _run_git(["rev-parse", "--show-toplevel"], cwd=cwd, runner=runner)
    if result.returncode != 0:
        raise InstallerError(
            f"git rev-parse --show-toplevel failed: {result.stderr.strip()}"
        )
    return Path(result.stdout.strip())


def configured_hooks_path(cwd: Path, *, runner: Runner = subprocess.run) -> str | None:
    """Return the raw ``core.hooksPath`` value, or ``None`` if it is unset."""
    result = _run_git(["config", "--get", "core.hooksPath"], cwd=cwd, runner=runner)
    if result.returncode != 0:
        return None
    value = result.stdout.strip()
    return value or None


def resolve_hook_directory(cwd: Path, *, runner: Runner = subprocess.run) -> Path:
    """Return the directory Git will actually search for hooks from ``cwd``.

    Git documents ``core.hooksPath`` as resolved relative to the working
    tree in use, not to the primary checkout -- which is why this
    repository's owner keeps a ``.githooks/`` copy in every clone that wants
    Graphify's hooks active (AGENTS.md / AGENT_NOTES.md say so explicitly).
    An unset value falls back to the common Git directory's own ``hooks/``,
    which every worktree *does* share.
    """
    hooks_path = configured_hooks_path(cwd, runner=runner)
    if hooks_path is None:
        return git_common_dir(cwd, runner=runner) / "hooks"
    candidate = Path(hooks_path)
    if candidate.is_absolute():
        return candidate
    # Against the worktree root, not ``cwd``: Git runs a hook from the top
    # of the working tree, so that is what a relative ``core.hooksPath``
    # resolves against. Resolving against ``cwd`` instead put the wrapper
    # in `<subdir>/.githooks` whenever the installer was run from anywhere
    # but the root -- a write that succeeds, reports success, and leaves
    # the hook somewhere Git will never look.
    return repo_root(cwd, runner=runner) / candidate


def list_worktrees(cwd: Path, *, runner: Runner = subprocess.run) -> list[Path]:
    """Return every worktree Git reports, including the primary checkout."""
    result = _run_git(["worktree", "list", "--porcelain"], cwd=cwd, runner=runner)
    if result.returncode != 0:
        raise InstallerError(f"git worktree list failed: {result.stderr.strip()}")
    paths = []
    for line in result.stdout.splitlines():
        if line.startswith("worktree "):
            paths.append(Path(line[len("worktree ") :]))
    return paths


def _is_under(path: Path, boundary: Path) -> bool:
    """Whether ``path`` equals or sits beneath ``boundary``, both resolved."""
    try:
        path.resolve().relative_to(boundary.resolve())
        return True
    except ValueError:
        return False


def hook_directory_is_contained(
    hook_directory: Path, *, worktree_root: Path, common_dir: Path
) -> bool:
    """Whether the resolved hook directory stays inside a trusted boundary.

    A configured ``core.hooksPath`` is an arbitrary string: an absolute path
    outside the repository entirely, or a relative one laced with ``..``,
    would make ``--install`` write a Git hook file somewhere this
    repository does not own. The only two locations this installer trusts
    are the worktree it was asked to act on and the shared common Git
    directory (where the default, unconfigured ``hooks/`` already lives).
    Resolving both sides here (not just trusting the caller's inputs)
    collapses any ``..`` segments before the comparison, so an escape is
    caught even when ``resolve_hook_directory`` returned an unnormalized
    path.
    """
    return _is_under(hook_directory, worktree_root) or _is_under(
        hook_directory, common_dir
    )


# --------------------------------------------------------------------- #
# Interpreter resolution                                                 #
# --------------------------------------------------------------------- #


def qualified_python(
    primary_root: Path,
    *,
    os_name: str = None,
    access: Callable[..., bool] = None,
) -> Path:
    """Return the primary checkout's qualified Python, or fail closed.

    Mirrors ``docsync_preflight.require_python``: installing a wrapper that
    invokes an unqualified interpreter would reproduce, at commit time on
    every future commit, exactly the retired-environment hazard AGENTS.md
    Environment Setup already warns about.
    """
    os_name = os.name if os_name is None else os_name
    access = os.access if access is None else access
    table = WINDOWS_TOOLS if os_name == "nt" else POSIX_TOOLS
    candidate = primary_root / ".venv" / table["python"]
    if not is_runnable(candidate, os_name=os_name, access=access):
        raise InstallerError(
            f"No qualified Python interpreter at {candidate}. Follow the "
            "AGENTS.md Environment Setup section in the primary checkout "
            "before installing this hook."
        )
    return candidate


# --------------------------------------------------------------------- #
# Hook content                                                           #
# --------------------------------------------------------------------- #


def render_hook_script(*, python_exe: Path, preflight_script: Path) -> str:
    """Render the generated wrapper's exact text, always LF-terminated.

    Docsync runs first and unconditionally, before any other pre-commit
    hook can touch the candidate: that ordering is the whole point of this
    wrapper (see ".pre-commit-config.yaml" and the "Commit preflight"
    design section) -- unless the operator named this hook's own id,
    ``doc-state-sync-check``, in ``SKIP`` (pre-commit's own comma-separated
    skip list). That is the one owner-approved local escape for a commit
    that must touch docsync's own control-plane code, which the preflight
    step otherwise refuses on principle; disabling hooks outright is a
    forbidden practice this wrapper does not offer (see AGENTS.md /
    CLAUDE.md). Skipping only bypasses the preflight step below -- delegation
    to pre-commit's own hooks always still happens, and pre-commit applies
    the same SKIP value again there, independently, for every hook it runs.
    It then delegates to ``pre_commit hook-impl`` directly -- the same
    low-level entry point ``pre-commit install`` itself generates -- instead
    of through Git's own hook dispatch, which is what keeps this
    non-recursive: ``hook-impl`` runs the configured hooks in-process and
    never re-enters ``core.hooksPath``.
    """
    python_posix = python_exe.as_posix()
    preflight_posix = preflight_script.as_posix()
    lines = [
        "#!/bin/sh",
        GENERATED_MARKER,
        "# Do not edit by hand; re-run scripts/dev/install_docsync_hook.py "
        "--install --yes to regenerate.",
        "#",
        "# Docsync runs first and unconditionally, before any other",
        "# pre-commit hook can touch the candidate -- unless SKIP names",
        "# this hook's own id below, which is the one owner-approved local",
        "# escape for a commit that must touch docsync's own control-plane",
        "# code. This wrapper then delegates to `pre_commit hook-impl`",
        "# directly instead of through git's own hook dispatch, which is",
        "# what keeps it non-recursive: hook-impl runs the configured",
        "# hooks in-process and never re-enters hooksPath.",
        'case ",$SKIP," in',
        "    *,doc-state-sync-check,*)",
        "        skip_docsync=1",
        "        ;;",
        "    *)",
        "        skip_docsync=0",
        "        ;;",
        "esac",
        'if [ "$skip_docsync" -ne 1 ]; then',
        f'    "{python_posix}" "{preflight_posix}" --staged',
        "    status=$?",
        '    if [ "$status" -ne 0 ]; then',
        '        exit "$status"',
        "    fi",
        "fi",
        f'exec "{python_posix}" -m pre_commit hook-impl '
        '--config=.pre-commit-config.yaml --hook-type=pre-commit -- "$@"',
        "",
    ]
    return "\n".join(lines)


def classify_existing_hook(path: Path) -> str:
    """Classify what occupies ``path``: ``absent``, ``ours``, or ``unknown``."""
    if not path.exists():
        return "absent"
    try:
        content = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return "unknown"
    return "ours" if GENERATED_MARKER in content else "unknown"


# --------------------------------------------------------------------- #
# Inspection / installation report                                       #
# --------------------------------------------------------------------- #


@dataclass(frozen=True)
class Disclosure:
    """Everything a caller must see before this installer may write anything."""

    primary_root: Path
    hooks_path_config: str | None
    hook_directory: Path
    hook_path: Path
    worktrees: tuple[Path, ...]
    existing_status: str

    def render(self) -> str:
        """Render the disclosure the same way for --check and --install."""
        lines = [
            f"Primary checkout: {self.primary_root}",
            (
                f"core.hooksPath: {self.hooks_path_config}"
                if self.hooks_path_config is not None
                else "core.hooksPath: (unset; using the common .git/hooks directory)"
            ),
            f"Resolved hook directory: {self.hook_directory}",
            f"Target hook file: {self.hook_path}",
            f"Existing hook file: {self.existing_status}",
            f"Worktrees this hook directory affects ({len(self.worktrees)}):",
        ]
        lines.extend(f"  - {worktree}" for worktree in self.worktrees)
        return "\n".join(lines)


def inspect(cwd: Path, *, runner: Runner = subprocess.run) -> Disclosure:
    """Build the full disclosure for ``cwd`` without writing anything."""
    primary_root = primary_checkout_root(cwd, runner=runner)
    hooks_path_config = configured_hooks_path(cwd, runner=runner)
    hook_directory = resolve_hook_directory(cwd, runner=runner)
    hook_path = hook_directory / HOOK_NAME
    worktrees = tuple(list_worktrees(cwd, runner=runner))
    return Disclosure(
        primary_root=primary_root,
        hooks_path_config=hooks_path_config,
        hook_directory=hook_directory,
        hook_path=hook_path,
        worktrees=worktrees,
        existing_status=classify_existing_hook(hook_path),
    )


def install(
    cwd: Path,
    *,
    runner: Runner = subprocess.run,
    yes: bool = False,
    os_name: str = None,
    access: Callable[..., bool] = None,
    print_fn: Callable[[str], None] = print,
) -> int:
    """Disclose scope, then write the wrapper only when ``yes`` is true.

    Returns 0 on a successful install (or a no-op dry run), 2 when a
    precondition fails (missing interpreter, an unknown existing hook, an
    out-of-repository target, or a Git failure).
    """
    try:
        disclosure = inspect(cwd, runner=runner)
        worktree_root = repo_root(cwd, runner=runner)
        common_dir = git_common_dir(cwd, runner=runner)
    except InstallerError as exc:
        print_fn(f"ERROR {exc}")
        return 2

    print_fn(disclosure.render())

    # Containment is enforced only here, by --install -- never by --check
    # (`inspect()` above), which stays purely informational so an operator
    # can still see an unsafe configured target without this function
    # refusing on their behalf before they asked it to write anything.
    if not hook_directory_is_contained(
        disclosure.hook_directory, worktree_root=worktree_root, common_dir=common_dir
    ):
        print_fn(
            f"ERROR {disclosure.hook_directory} is outside this repository "
            f"(neither the worktree at {worktree_root} nor the common Git "
            f"directory at {common_dir}). Refusing to install a hook there "
            "-- fix core.hooksPath, or run this installer from the "
            "checkout that value is meant for."
        )
        return 2

    if not yes:
        print_fn(
            "Dry run: nothing was written. Pass --yes to install the wrapper "
            "at the target hook file shown above."
        )
        return 0

    if disclosure.existing_status == "unknown":
        print_fn(
            f"ERROR {disclosure.hook_path} already exists and was not "
            "generated by this installer. Refusing to overwrite it -- move "
            "it aside (or fold its logic into the wrapper by hand) and "
            "re-run this installer."
        )
        return 2

    try:
        python_exe = qualified_python(
            disclosure.primary_root, os_name=os_name, access=access
        )
    except InstallerError as exc:
        print_fn(f"ERROR {exc}")
        return 2

    preflight_script = disclosure.primary_root / PREFLIGHT_SCRIPT
    script_text = render_hook_script(
        python_exe=python_exe, preflight_script=preflight_script
    )
    disclosure.hook_directory.mkdir(parents=True, exist_ok=True)
    # write_bytes, not write_text: write_text's default newline handling
    # translates every "\n" to the platform line separator, which on
    # Windows would reintroduce the exact CRLF-hook failure AGENTS.md /
    # AGENT_NOTES.md already document for `.githooks/post-commit` under
    # Git for Windows' `sh`.
    disclosure.hook_path.write_bytes(script_text.encode("utf-8"))
    if os.name != "nt":
        os.chmod(disclosure.hook_path, 0o755)

    verb = "Reinstalled" if disclosure.existing_status == "ours" else "Installed"
    print_fn(f"{verb} the docsync preflight wrapper at {disclosure.hook_path}.")
    return 0


# --------------------------------------------------------------------- #
# CLI                                                                     #
# --------------------------------------------------------------------- #


def _build_parser() -> argparse.ArgumentParser:
    """Declare the read-only default, the explicit apply, and its gate."""
    parser = argparse.ArgumentParser(
        description=(
            "Inspect (default) or install the docsync-first pre-commit hook wrapper."
        )
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Read-only inspection (the default; writes nothing).",
    )
    parser.add_argument(
        "--install",
        action="store_true",
        help="Disclose scope and, only with --yes, write the wrapper.",
    )
    parser.add_argument(
        "--yes",
        action="store_true",
        help="Required alongside --install to actually write the wrapper.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Parse arguments and run inspection or the gated install."""
    args = _build_parser().parse_args(argv)
    if args.check and args.install:
        print("Use --check or --install, not both.", file=sys.stderr)
        return 2
    cwd = Path.cwd()
    if args.install:
        return install(cwd, yes=args.yes)
    print(inspect(cwd).render())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
