name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      FLASK_ENV: development

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pre-commit checks
        run: |
          pip install pre-commit
          pre-commit run --all-files

      - name: Lint code with flake8
        continue-on-error: false
        run: |
          pip install flake8
          flake8 --config .flake8

      - name: Run Tests with Coverage
        run: |
          pytest --cov=./ --cov-report=xml
          